[package]
name = "spool_server"
version = "0.1.0"
authors = ["Your Name <your.email@example.com>"]
edition = "2018"

[dependencies]
tonic = "0.5"
prost = "0.8"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
tonic-build = "0.5"