[package]
name = "config_lib"
version = "0.1.0"
authors = ["Brett Chaldecott <brett.chaldecott@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.11"
serde = { version = "1.0", features = ["derive"] }
environment_lib = { path = "../environment_lib" }
